#Description,Server,SSL,UTF8,3Step,Delete,ApacheBackslash
#Some providers
1und1 (Germany),sd2dav.1und1.de,1,0,0,1,0
GMX Secure Server,webdav.mc.gmx.net,1,1,0,1,0
T-Online Secure Server,webdav.mediencenter.t-online.de,1,1,1,0,0
Xythos (Sharemation.com),www.sharemation.com/<your account>/,0,1,0,0,0

#standard server types
Apache on Linux,,0,0,0,0,1
BarracudaDrive,<your server>/fs/,1,1,0,0,1
Microsoft IIS,,0,1,1,0,0
Microsoft IIS (Secure),,1,1,1,0,0
Tamino (Software AG),,0,1,0,0,0

